services:
  server:
    build:
      context: .
      dockerfile: deploy/server/Dockerfile
    command: >
      sh -c "
             while ! nc -z db 5432; do
               echo 'Waiting for database to be ready...'
               sleep 2
             done
             echo 'Database is ready!'
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_HOST=db  # Override DATABASE_HOST to use the service name
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: deploy/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
