version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: deploy/server/Dockerfile
    command: >
      sh -c "
             while ! nc -z db 5432; do
               echo 'Waiting for database to be ready...'
               sleep 2
             done
             echo 'Database is ready!'
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/basic_api
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: deploy/postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
