# Generated by Django 5.0.6 on 2025-02-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(),
        ),
    ]
